FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# questionaries

Questions

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        { "questions":[
            {
                "question": "question 1?",
                "input_type": "text",
                "mandatory":true,
                "answer":""
                    
            },
        

            {
                
                "question": "question 2?",
                "input_type":"radio",
                "mandatory":false,
                "answer":"",
                "options":[
                            {"id":"Male"},
                            {"id":"Female"}
                         ]
         },
               
        
            {
                "question": "question 3?",
                "input_type": "checkbox",
                "mandatory":true,
                "answer":[],
                "options":[
                             {"id":"Home Address"},
                             {"id":"Office Address"}
                         ]
              },
              
            {
                
                "question": "question 4?",
                "input_type": "text",
                "mandatory":true,
                "answer":""
                    
            },
            {
                
                "question": "question 5?",
                "input_type": "text",
                "mandatory":false,
                "answer":""
                    
            }
        
        ]
        }