FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# addressAPI

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/Address]



### Create a New Question [POST]



+ Request (application/json)

        {
         "Address": {
         "name": " ",
         "Surname": " ",
         "Phone number": " ",
         "Address": " "
         }
        }

+ Response 201 (application/json)

    + Headers

            Location: /Address/2

    + Body

            {
              "Address": {
              "name": "Shabana",
             "Surname": "shaik ",
               "Phone number": " 12345",
                        "Address": "51-980"
                    }
                    }